executor: KubernetesExecutor

env: 
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "false"

postgresql:
  enabled: false

data:
  metadataConnection:
    user: airflow
    pass: airflow123
    host: postgres-service.dados.svc.cluster.local
    port: 5432
    db: pipeline
    protocol: postgresql


dags:
  gitSync:
    enabled: true
    repo: https://github.com/mariaeac/pipeline-k8s
    branch: main
    subPath: pipeline-k8s/dags
    period: 30s

apiServer:
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10